# Generated by Django 3.2.6 on 2021-09-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210928_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
